### ISSUE TITLE
Some additional info to README

### ISSUE THREAD

**Issue by randykindling** [Gananath/DrugAI#3]
Hi!
It may be usefull to add info for newbies in python about back end selection in keras
Im using win7, where tensorflow for python 2.7 is not supported, so I must change keras.json to 
{
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "**theano**",
    "image_data_format": "channels_last"
}  
An option exists to change backend to "cntk", I tryed to do this without success

**Comment by Gananath** [comment]
Hi randykindling,
Thank you for your suggestion but the solution for this is widely available in the web. A quick googling alone gets us thousands of answers and because of that I think for now I am  going to put a hold on this suggestion. Anyways thank you for using this and If you have any more recommendations or questions please feel free to contact me.
